### ISSUE TITLE
undefined: netFD while trying to run a simple http server

### ISSUE THREAD

**Issue by agnivade** [neelance/go#1]
This is the code 

```go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello, world")
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

Trying to compile this gives - 
```
GOOS=js GOARCH=wasm ./bin/go build -o net.wasm wasm_net.go 
# net
src/net/net.go:164:6: undefined: netFD
```

If you can point me out to the area where it needs to be worked, I will be happy to look into it. Really looking forward to Go integration for wasm and will be glad to help out in any capacity.

**Comment by agnivade** [comment]
Ah my bad. I see that `test_all.sh` doesn't support the net package yet. Can you give me some pointers to where I can start to support the net package ?

**Comment by agnivade** [comment]
Looked into it. The build tag js is missing for platform specific files under `src/net`. Not sure how you want to do this. Do you just want to add the js tag on all files ? But then if there are different implementations for unix and windows, how do we handle that ?

**Comment by neelance** [comment]
HTTP servers are unlikely to be supported soon, because they would never work in web browsers.

**Comment by neelance** [comment]
Oops, didn't intend to close right away.

**Comment by agnivade** [comment]
I see. Understood.

I have a general question though - Since you are using build tags to control the build output, what if we have a Go file which has different implementation for unix and windows ? How are we handling that case ?

Thanks for your work.

**Comment by neelance** [comment]
Those packages will need to target `js/wasm` as well, since it would probably need a different implementation anyways.

**Comment by sbinet** [comment]
shouldn't we also plan to support say `linux/wasm`, `darwin/wasm`, ... too ?
so, _e.g._, one could instantiate a `wasm` module with definitions for `println`, `runtime.nanotime`, ... that call into a "host-module" instead of the `js` `importObject` that you define in the `nodejs` bootstrap code.
this would allow to directly execute the `wasm` module w/o a javascript VM.

**Comment by neelance** [comment]
How would you do that? Which WebAssembly compiler/runtime would you use?

**Comment by neelance** [comment]
Also: Why would you want to run WebAssembly like that? Isn't it easier to simply compile Go to that target in the usual way? WebAssembly is only really useful in the web browser.

**Comment by sbinet** [comment]
wasm is a nice bytecode standard (one that is bound to be widespread, thanks to its web support)
why wouldn't one want to run it directly, w/o a browser ?

[wagon/cmd/wasm-run](https://github.com/go-interpreter/wagon) can already interpret and run a fair set of the official wasm testsuite. (imports aren't supported right now, though)
one could dream of `wagon` being, eventually, a complete Go interpreter, written in Go, consuming wasm bytecode that has been compiled with `go` :)

**Comment by neelance** [comment]
What are the practical advantages compared to compiling Go directly to the target architecture?

**Comment by sbinet** [comment]
you get a REPL :)

**Comment by neelance** [comment]
A REPL? How?

**Comment by sbinet** [comment]
with a wasm module, you get something that is more amenable to being interpreted by an interpreter.
once you have an interpreter that can ingest wasm bytecode, you can build an interactive interpreter on top of that: you have your REPL.

you could of course directly interpret the Go source code, either using directly the AST (such as [here](https://github.com/sbinet/igo), or [there](https://neugram.io) or [there](https://github.com/cosmos72/gomacro)) or using SSA (such as [there](https://github.com/go-interpreter/ssainterp)).
but having a VM that can interpret bytecode is a more efficient way to get at a REPL. (that's what CPython, PyPy, Ruby, ... all do, in the end.)

**Comment by neelance** [comment]
> once you have an interpreter that can ingest wasm bytecode, you can build an interactive interpreter on top of that: you have your REPL.

It doesn't work that way. The Go compiler always emits a fully linked application.

**Comment by agnivade** [comment]
> Those packages will need to target js/wasm as well, since it would probably need a different implementation anyways.

This may be a stupid question. But how can a single wasm implementation of a package support both linux and windows, when they have different implementations in Go for linux and windows ? Is there some wasm specific code which works at a level above the OS layer ?

**Comment by neelance** [comment]
Here's the layer: https://github.com/neelance/go/blob/wasm-wip/misc/wasm/wasm_exec.js#L130

**Comment by agnivade** [comment]
Ahh thanks. I think I get it now. Thanks for your patience. Closing this now as my questions are answered.
