### ISSUE TITLE
`Invoke` should behave consistently for any receivers

### ISSUE THREAD

**Issue by hajimehoshi** [neelance/go#13]
Sorry for my persistent demand, but I'd like to reach the consensus.

As I reported, `Invoke` calls the receiver asyncly for a `Callback`, and calls the receiver immediately for a regular function. For example,

```go
package main

import (
        "syscall/js"
)

func main() {
        c := js.NewCallback(func(args []js.Value) {
                println("callback")
        })
        defer c.Dispose()

        f := js.Global.Call("eval", "(function() { console.log('function') })")
        js.ValueOf(c).Invoke()
        f.Invoke()
}
```

shows `function` but not `callback`.

From the signature of `Invoke` having a return value, I think it is natural to expect `Invoke` executes the receiver immediately, but actually whether the receiver is executed immediately depends on whether the receiver is function or callback. I feel like it is inconsistent or hard to expect.

I'd want `Invoke` to behave more consistently, which means it always executes the receiver immediately, or it always executes the receiver asyncly and returns nothing (this would require to change the signature). I think the former is ideal, but the latter is also better than the current state.

**Comment by hajimehoshi** [comment]
As @neelance and I discussed at the Slack, now I understood that `js.NewCallback` creates a JavaScript function including a Go function internally, and `Invoke` invokes the JavaScript function to push the Go function to the queue, and doesn't care when the internal Go function is invoked.

Hmm, that seems to make sense. How about documentation about this?

**Comment by neelance** [comment]
`js.NewCallback` has a doc comment now. I hope it helps to avoid this issue.

**Comment by hajimehoshi** [comment]
Thank you!

2018年5月24日(木) 7:43 Richard Musiol <notifications@github.com>:
