### ISSUE TITLE
js.ValueOf(0).Length() returns -4294967296

### ISSUE THREAD

**Issue by hajimehoshi** [neelance/go#15]
```go
package main

import (
        "syscall/js"
)

func main() {
        println(js.ValueOf(0).Length())
}
```

shows

```
-4294967296
```

Is this intended?

Tested with dca597e2fe476a10d5ada2744245a56f60720ddf.

**Comment by neelance** [comment]
`(0).length` is `undefined`. `parseInt(undefined)` is `NaN`. And `NaN` turns into this number... Yes, we probably want something else here. Not sure what though...

**Comment by hajimehoshi** [comment]
How about just panicing?

**Comment by neelance** [comment]
`js.Undefined.Int()` also gives 0.

**Comment by neelance** [comment]
I think if we want to panic here, then we would need to do so on anything that is not a `number` by doing a strict type check. But I'm not yet convinced that this would be the better way to go.

**Comment by neelance** [comment]
Right now I don't have enough indicators that it would be good to change this. I'll close this for now since I am retiring this issue tracker. Please reopen on `golang/go` if you'd like to see more discussion on the topic.
