### ISSUE TITLE
Suggestion: Allow `[]float32` or other arrays to `js.ValueOf`

### ISSUE THREAD

**Issue by hajimehoshi** [neelance/go#19]
This would be useful for WebGL functions: for example, `uniformMatrix4fv` accepts only `Float32Array` at the third argument.

**Comment by neelance** [comment]
I'm leaning towards supporting this. Would you mind moving this to the Go issue tracker so we can have other members of the Go team help with how to decide what to add to an API?

**Comment by hajimehoshi** [comment]
Done :-)

**Comment by shurcooL** [comment]
For posterity, it's issue golang/go#25532.

**Comment by neelance** [comment]
Closing here.
