### ISSUE TITLE
Question: Channels in wasm

### ISSUE THREAD

**Issue by FlorianUekermann** [neelance/go#2]
As GopherJS author (thanks!) you are well aware of the problems that arise when implementing Go channels in JS. Does wasm provide ways to block while waiting for something else to happen, or will the wasm implementation suffer from the same problems as GopherJS (crash in case of temporary deadlocks).

**Comment by neelance** [comment]
"temporary deadlock" is an interesting term. ;-) I guess what you're talking about is that the Go application is waiting for some callback from the JS world? In fact, this should work fine with GopherJS, maybe you could provide some example code for your issue. With wasm I don't know yet how exactly to solve this, but I'm quite confident that I there will be a solution.

**Comment by FlorianUekermann** [comment]
> "temporary deadlock" is an interesting term. ;-) I guess what you're talking about is that the Go application is waiting for some callback from the JS world?

Yep, that's what I'm talking about.

> In fact, this should work fine with GopherJS

Yes. I've read your GopherJS scheduling code (cool idea btw) and agree it should work in most cases. The exception is waiting on a channel in code that is called from JS (or a JS callback). So I've been wondering if wasm provides a way around that. The simplest example would be a call to time.Sleep or an http request.

OT, regarding GopherJS: I would really like to document more precisely which cases fail, since it is the only serious deviation from the go spec. After reading your code I've come to the conclusion that GopherJS implements pretty stronger guarantees, without documenting them. I would really appreciate if you could confirm that at gopherjs/gopherjs#720, so I can send a pull request documenting the situation.
