### ISSUE TITLE
control over export

### ISSUE THREAD

**Issue by sbinet** [neelance/go#22]
I am trying to explicitly export a given Go function (compiled to wasm).

compiling `main.go`:
```go
package main

func main() {
	println("hello")
	println("1+3=", MyAdd(1, 3))
}

//export MyAdd
func MyAdd(i, j int32) int32 {
	return i + j
}
```

like so (using a0889bfea7):
```
$> GOOS=js GOARCH=wasm go build -o foo.wasm ./main.go
```

I get:
```
$> ./run.sh 
+ /bin/rm -f foo.wasm
+ go build -o foo.wasm ./main.go
+ wasm-objdump -h ./foo.wasm

foo.wasm:	file format wasm 0x1

Sections:

     Type start=0x0000000e end=0x00000048 (size=0x0000003a) count: 10
   Import start=0x0000004e end=0x000000ce (size=0x00000080) count: 6
 Function start=0x000000d4 end=0x0000042c (size=0x00000358) count: 854
    Table start=0x00000432 end=0x00000437 (size=0x00000005) count: 1
   Memory start=0x0000043d end=0x00000442 (size=0x00000005) count: 1
   Global start=0x00000448 end=0x0000047b (size=0x00000033) count: 10
   Export start=0x00000481 end=0x0000048f (size=0x0000000e) count: 2
     Elem start=0x00000495 end=0x00000acf (size=0x0000063a) count: 1
     Code start=0x00000ad5 end=0x000a3b7a (size=0x000a30a5) count: 854
     Data start=0x000a3b80 end=0x001290fd (size=0x0008557d) count: 7
   Custom start=0x00129103 end=0x0012f117 (size=0x00006014) "name"
+ wasm-objdump -j export -x ./foo.wasm

foo.wasm:	file format wasm 0x1

Section Details:

Export:
 - func[750] <_rt0_wasm_js> -> "run"
 - memory[0] -> "mem"
```

would it be possible to wire-in the `//export Foo` Go machinery into the `wasm` file export machinery?

**Comment by neelance** [comment]
This is not possible, because Go has a runtime with goroutines, garbage collection, etc.
Please use `js.NewCallback` to expose additional entry points.

**Comment by sbinet** [comment]
I understand Go has a "heavy" runtime that needs to cooperate with the browser Js VM.
I also understand that, with the lack of support for threads and GC in the current MVP wasm standard, exposing/exporting directly a Go function to the JS world via a wasm module may not be a good idea.

indeed, one needs to setup a bunch of things for the 2 runtimes (Go's and Js') to correctly cooperate.
but the same is true when one create a `.so` with `-buildmode=c-shared`.

what I am getting at is that when building with `GOOS=js GOARCH=wasm` (and possibly with `-buildmode=c-shared`), a function decorated with:
```go
//export Foo
func Foo(...) T { ... }
```

could probably be compiled-in with all the needed `js` wrapping/unwrapping to expose it correcly to the web-browser, and have it nitely folded inside the `export` section.

one could use the module' [start](https://webassembly.org/docs/modules/#module-start-function) function to setup the Go runtime.

**Comment by neelance** [comment]
`-buildmode=c-shared` is a good point. It might be possible, but it's not on the roadmap yet. I also don't see why this would be necessary for browsers. Callbacks should do just fine.

**Comment by sbinet** [comment]
for browsers, sure.
but I'd like (eventually) to have other backends, and matching the "original" Go export semantics as closely as possible seems like a good idea.

**Comment by sbinet** [comment]
(should I file something against golang/go so we don't forget about this?)

**Comment by neelance** [comment]
Yes, please do.

**Comment by sbinet** [comment]
done.
