### ISSUE TITLE
Comparing number objects fails

### ISSUE THREAD

**Issue by hajimehoshi** [neelance/go#27]
```go
package main

import (
        "syscall/js"
)

func main() {
        n := js.Global.Get("Number")
        println(n.New(1) == n.New(1))
}
```

Shows `false`, I expected `true` though.

This might be intended, but was really confusing to me. For example, getting WebGL's constant like `FRAMEBUFFER_COMPLETE` via `Get` creates a number object, and comparing another value and the constant always fails.

```go
// gl is a WebGL context of a canvas.
gl.Call("framebufferTexture2D", gl.Get("FRAMEBUFFER"), gl.Get("COLOR_ATTACHMENT0"), gl.Get("TEXTURE_2D"), js.Value(t), 0)
if s := gl.Call("checkFramebufferStatus", gl.Get("FRAMEBUFFER")); s != gl.Get("FRAMEBUFFER_COMPLETE") {
        // This always comes here!
        return js.Null, errors.New(fmt.Sprintf("opengl: creating framebuffer failed: %d", s.Int()))
}
```

**Comment by neelance** [comment]
This is about the equality of two `js.Value` in general. We currentlt can't rely on the `==` operator in Go. Please open this issue on `golang/go`, since there is no quick solution and it needs some discussion.

**Comment by hajimehoshi** [comment]
Done. Thank you for replying :-)
