### ISSUE TITLE
Not work simple example.

### ISSUE THREAD

**Issue by prospero78** [neelance/go#30]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11.4

### Does this issue reproduce with the latest release?
Special for this case download latest version -- 1.11.5.
Now naffit change.

### What operating system and processor architecture are you using (`go env`)?
Intel Celeron N3050 (2 kernel), Windows 10 Corporate 64 bit, RAM 4 GB.

```
set GOARCH=wasm
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=js
set GOPATH=d:\coding\golang\_home_
set GOPROXY=
set GORACE=
set GOROOT=D:\coding\golang
set GOTMPDIR=
set GOTOOLDIR=D:\coding\golang\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 
-fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build643109782=/tmp/go-build 
-gno-record-gcc-switches
```

### What did you do?
I tried to execute the example that is located on the link on the main page of wasmgo.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Testing web page not work. In console this message:
```
LinkError: WebAssembly Instantiation: Import #5 module="go" function="runtime.scheduleCallback" 
error: function import requires a callable
WebAssembly.instantiateStreaming.then.catch @ (index):35
Promise.catch (async)
(anonymous) @ (index):34
```
(* Windows 10 64 bit, Chrome 71 (64 bit, go 1.11.5 64 bit *)

In Firefox (vers. 63, 64 bit):
```
LinkError: "import object field 'runtime.scheduleCallback' is not a Function" localhost:8080:35:4
<anonymous>
http://localhost:8080/:35:4
```

### What did you see instead?
Error in the Chrome Developer Console is full text above.......

**Comment by neelance** [comment]
This issue tracker is unmaintained, use the main Go repository instead.
