### ISSUE TITLE
Crash after execution on Firefox 59.0b13 (64-bit)

### ISSUE THREAD

**Issue by johanbrandhorst** [neelance/go#4]
Hi!

I just tried compiling and running some WASM code and I think it crashed. All the code I used is contained in https://github.com/johanbrandhorst/wasm-experiments/tree/master/printing. I included the compiled WASM output as well (./html/test.wasm).

This is what I see when I run it in firefox:

![wasm](https://user-images.githubusercontent.com/6604151/36873219-bb5e2c0e-1d9f-11e8-8515-711b52a1591b.png)

Seems to execute fine and then crash in the JS loader? I cannot tell.

**Comment by kripken** [comment]
The RuntimeError is from inside wasm - it is accessing an invalid address in linear memory. Firefox debugger says it's the `store` at offset 0x68517.

**Comment by neelance** [comment]
I hadn't tested with a browser for a while, only with Node.js. It is fixed now. The issue was that the code didn't properly stop running on exit.

**Comment by johanbrandhorst** [comment]
Happy to help! I'll continue playing with it.
