### ISSUE TITLE
Unexpected panic when using callback

### ISSUE THREAD

**Issue by johanbrandhorst** [neelance/go#9]
Hi!

I was trying out the new `syscall/js/callback` package, and I'm wondering if I'm using it correctly. The entire source for my test can be found on [my github](https://github.com/johanbrandhorst/wasm-experiments).

I'm getting a panic when passing a `syscall/js/callback.Callback` to `syscall/js.Value.Call`. My example looks like this (abbreviated):

```go
promise := js.Global.Call("fetch", "http://google.com")
promise.Call("then", callback.New(func(args []js.Value) {
    fmt.Println(args)
}))
```

This results in the following panic:

```bash
panic: invalid value wasm_exec.js:59:6
wasm_exec.js:59:6
goroutine 1 [running]: wasm_exec.js:59:6
syscall/js.ValueOf(0x3dc60, 0xc01e2d0, 0x1) wasm_exec.js:59:6
    $GOPATH/src/github.com/neelance/go/src/syscall/js/js.go:95 +0x90 wasm_exec.js:59:6
syscall/js.makeArgs(0xc077d68, 0x1, 0x1, 0x691a0, 0xc01e2b8, 0x691a0) wasm_exec.js:59:6
    $GOPATH/src/github.com/neelance/go/src/syscall/js/js.go:130 +0x7 wasm_exec.js:59:6
syscall/js.Value.Call(0x1a, 0x74e9f, 0x4, 0xc077d68, 0x1, 0x1, 0x1a) wasm_exec.js:59:6
    $GOPATH/src/github.com/neelance/go/src/syscall/js/js.go:141 +0x2 wasm_exec.js:59:6
github.com/johanbrandhorst/wasm-experiments/fetch/fetch.Fetch(0x1, 0xc0d2000, 0xc028b10, 0xc01e260, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, ...) wasm_exec.js:59:6
    $GOPATH/src/github.com/johanbrandhorst/wasm-experiments/fetch/fetch/fetch.go:73 +0x1f wasm_exec.js:59:6
main.main() wasm_exec.js:59:6
    $GOPATH/src/github.com/johanbrandhorst/wasm-experiments/fetch/main.go:25 +0xc
```

**Comment by shurcooL** [comment]
@johanbrandhorst This may or may not be related, bu the http://google.com URL doesn't permit CORS, so the code you tried to execute is expected to fail in browser:

![image](https://user-images.githubusercontent.com/1924134/39960864-64d2ff36-55f8-11e8-9d4e-cd11a5dc5364.png)

What happens if you try it on another URL, one that permits CORS? For example, https://api.github.com:

![image](https://user-images.githubusercontent.com/1924134/39960869-8593ed8e-55f8-11e8-97d6-f39fa778d2e6.png)

(Or did you try running this via Node.js? If so, CORS is probably not applicable.)

**Comment by johanbrandhorst** [comment]
@shurcooL Cool, I will switch out the URL, but the error occurs before the request is even made as far as I can tell.

I ran the example in Firefox. In my testing I wasn't able to use node without installing third party Fetch API polyfills.

**Comment by shurcooL** [comment]
Also, have you tried this?

```diff
 promise.Call("then", callback.New(func(args []js.Value) {
 	fmt.Println(args)
-}))
+}).Value)
```

Since `callback` package isn't documented yet, it's not clear to me how it's meant to be used.

**Comment by johanbrandhorst** [comment]
I couldn't see any way to interact with the `Callback` type other than using `Dispose`. Changing to use `.Value` removes the panic! Thanks for the tip!

**Comment by shurcooL** [comment]
It might be worthwhile to keep this open until @neelance gets a chance to see this.

I suspect there are API change opportunities to consider here, ones that could make the user experience better.

For example, perhaps `js.Call` should recognize `callback.Callback` type and report a better error. Or maybe it should extract its `Value` automatically (and then `Value` potentially be made unexported).

Given this is still a WIP, these things may already be on @neelance's mind and in future plans. :)

**Comment by johanbrandhorst** [comment]
Good points all, I'll reopen it and allow @neelance to choose what to do :).

**Comment by neelance** [comment]
Good feedback! Now that I merged the `callback` package into `syscall/js` I was able to allow `Callback` to be passed to `Value.Call` directly and make `Value` unexported.
